# fly.toml app configuration file generated for my-backend-late-star-5731 on 2025-05-19T13:19:23-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-backend-late-star-5731'
primary_region = 'dfw'

[build]

[[mounts]]
  source = 'tmp'
  destination = '/tmp'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
